basePath: /skeleton/1.0.0
consumes: [application/json]
definitions: {}
host: localhost:8080
info: {title: API Skeleton, version: 1.0.0}
paths:
  /hello:
    get:
      operationId: hello_world
      responses:
        200: {description: status supplied}
        500: {description: server error}
      x-swagger-router-controller: skeleton.skeleton
produces: [application/json]
schemes: [http, https]
swagger: '2.0'
