from pathlib import Path
from json import loads


class ONSInfo(object):
    """
    Manage the 'git_info' file generated by the jenkins build job and optionall
    add in 'version' and 'name' from the local environment/config. If no name is
    supplied it will fall back on the name generated by the jenkins build job, which
    is currently the Jenkins job name.
    """

    def __init__(self, env):
        """
        Initialise the object with the parent environment

        :param env: the ons_env environment
        """
        if Path('git_info').exists():
            with open('git_info') as io:
                self._info = loads(io.read())
        else:
            self._info = {}

        self._info = dict(self._info, **{
            'version': env.get('version', 'no version'),
            'name': env.get('name', self._info.get('name', 'no name'))
        })

    @property
    def health_check(self):
        return self._info

